import type { Locale } from "./i18n";

/**
 * Book-page text. The page uses the language of the edition on show (a
 * Hindi-only book gets Hindi labels even when the site is in Marathi), as on
 * the original site.
 */
export const PRODUCT_COPY = {
  mr: {
    home: "मुख्यपृष्ठ",
    ebooks: "ई-बुक्स",
    combos: "कॉम्बो पॅक्स",
    readersTrust: "वाचकांचा विश्वास",
    instantDelivery: "✓ लगेच डिजिटल डिलिव्हरी",
    only: "फक्त",
    taxes: "सर्व कर समाविष्ट (Inclusive of all taxes)",
    off: "सवलत",
    digitalOnly: "📄 हे केवळ Digital PDF E-Book आहे — कोणतीही Physical / Printed प्रत पाठवली जात नाही.",
    noRefund: "⚠️ एकदा PDF डाउनलोड केल्यानंतर परतावा (Refund) शक्य नाही.",
    buyNote: "सुरक्षित पेमेंट | UPI, Card, Netbanking · Login / Account ची गरज नाही",
    pages: "पाने",
    instantDownload: "लगेच डाउनलोड",
    howToBuy: "खरेदी करण्याची पद्धत / How to Buy",
    steps: [
      { label: "बटन दाबा", en: "Click" },
      { label: "पेमेंट करा", en: "Pay" },
      { label: "PDF मिळवा", en: "Download" },
      { label: "माझी पुस्तके", en: "My Books" },
    ],
    comboIncludes: "या कॉम्बोमध्ये समाविष्ट पुस्तके",
    description: "वर्णन / Description",
    securePayment: "सुरक्षित पेमेंट (Safe & Secure Payment)",
    share: "मित्रांना शेअर करा (SHARE LINK)",
    copied: "लिंक कॉपी झाली! / Link copied",
    faqTitle: "नेहमी विचारले जाणारे प्रश्न",
    relatedTitle: "तुम्हाला हे देखील आवडेल",
    relatedBody: "आमची इतर काही महत्वाची पुस्तके पहा",
    viewAll: "सर्व पहा",
    faq: [
      { q: "हे पुस्तक मला कसे मिळेल?", a: "पेमेंट यशस्वी झाल्यानंतर तुम्हाला लगेच Download Button दिसेल आणि PDF डाउनलोड होईल. पेमेंट करताना दिलेल्या मोबाईल नंबरवर पुस्तक PDF स्वरूपात WhatsApp वरही पाठवले जाते. ही लिंक याच मोबाईलवर ‘माझी पुस्तके’ मध्ये जतन राहते, त्यामुळे नंतरही पुन्हा डाउनलोड करता येते." },
      { q: "पेमेंट सुरक्षित आहे का?", a: "हो, Razorpay 100% सुरक्षित आहे. GooglePay, PhonePe, Paytm किंवा कार्डद्वारे पेमेंट करा." },
      { q: "मोबाईलवर वाचता येते का?", a: "हो! PDF फाइल कोणत्याही मोबाईल, लॅपटॉप किंवा टॅब्लेटवर वाचता येते." },
      { q: "हे Physical पुस्तक आहे का?", a: "नाही. हे पूर्णपणे Digital PDF E-Book आहे. कोणतीही Printed / Hard Copy पाठवली जात नाही." },
      { q: "किती डिव्हाइसवर वाचता येईल?", a: "PDF वर कोणतेही बंधन नाही — तुम्ही तुमच्या Mobile, Tablet, Laptop, Desktop — कोणत्याही डिव्हाइसवर वाचू शकता." },
      { q: "भविष्यात Update मिळेल का?", a: "कायद्यात महत्त्वाचे बदल झाल्यास आम्ही Updated Edition प्रकाशित करतो. Current Version ची माहिती Product Page वर दिली आहे." },
      { q: "हे पुस्तक कायदेशीर सल्ला देते का?", a: "नाही. हे पुस्तक केवळ संदर्भ आणि शैक्षणिक उद्देशाने आहे. हा कोणत्याही प्रकारचा कायदेशीर सल्ला (Legal Advice) नाही. तुमच्या विशिष्ट कायदेशीर समस्येसाठी नेहमी तज्ञ वकिलाचा सल्ला घ्या." },
    ],
  },
  hi: {
    home: "होम",
    ebooks: "ई-बुक्स",
    combos: "कॉम्बो पैक्स",
    readersTrust: "पाठकों का विश्वास",
    instantDelivery: "✓ तुरंत डिजिटल डिलीवरी",
    only: "केवल",
    taxes: "सभी कर शामिल (Inclusive of all taxes)",
    off: "छूट",
    digitalOnly: "📄 यह केवल Digital PDF E-Book है — कोई Physical / Printed प्रति नहीं भेजी जाती।",
    noRefund: "⚠️ PDF डाउनलोड के बाद Refund संभव नहीं है।",
    buyNote: "सुरक्षित भुगतान | UPI, Card, Netbanking · Login / Account की ज़रूरत नहीं",
    pages: "पृष्ठ",
    instantDownload: "तुरंत डाउनलोड",
    howToBuy: "खरीदने की प्रक्रिया / How to Buy",
    steps: [
      { label: "बटन दबाएं", en: "Click" },
      { label: "भुगतान करें", en: "Pay" },
      { label: "PDF पाएं", en: "Download" },
      { label: "मेरी किताबें", en: "My Books" },
    ],
    comboIncludes: "इस कॉम्बो में शामिल किताबें",
    description: "विवरण / Description",
    securePayment: "सुरक्षित भुगतान (Safe & Secure Payment)",
    share: "दोस्तों को शेयर करें (SHARE LINK)",
    copied: "लिंक कॉपी हो गई! / Link copied",
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    relatedTitle: "आपको यह भी पसंद आएगा",
    relatedBody: "हमारी कुछ और महत्वपूर्ण किताबें देखें",
    viewAll: "सभी देखें",
    faq: [
      { q: "यह पुस्तक मुझे कैसे मिलेगी?", a: "भुगतान सफल होते ही आपको Download बटन दिखेगा और PDF डाउनलोड हो जाएगी। भुगतान के समय दिए गए मोबाइल नंबर पर पुस्तक PDF के रूप में WhatsApp पर भी भेजी जाती है। यह लिंक इसी मोबाइल पर ‘मेरी किताबें’ में सेव रहती है, इसलिए बाद में भी दोबारा डाउनलोड कर सकते हैं।" },
      { q: "क्या भुगतान सुरक्षित है?", a: "हाँ, Razorpay 100% सुरक्षित है। GooglePay, PhonePe, Paytm या कार्ड से भुगतान करें।" },
      { q: "क्या मोबाइल पर पढ़ा जा सकता है?", a: "हाँ! PDF फाइल किसी भी मोबाइल, लैपटॉप या टैबलेट पर पढ़ी जा सकती है।" },
      { q: "क्या यह Physical पुस्तक है?", a: "नहीं। यह पूरी तरह Digital PDF E-Book है। कोई Printed / Hard Copy नहीं भेजी जाती।" },
      { q: "कितने डिवाइस पर पढ़ सकते हैं?", a: "PDF पर कोई पाबंदी नहीं — आप अपने Mobile, Tablet, Laptop, Desktop — किसी भी डिवाइस पर पढ़ सकते हैं।" },
      { q: "क्या भविष्य में Update मिलेगा?", a: "कानून में महत्वपूर्ण बदलाव होने पर हम Updated Edition प्रकाशित करते हैं। Current Version की जानकारी Product Page पर दी गई है।" },
      { q: "क्या यह पुस्तक कानूनी सलाह देती है?", a: "नहीं। यह पुस्तक केवल संदर्भ और शैक्षणिक उद्देश्य के लिए है। यह किसी भी प्रकार की कानूनी सलाह (Legal Advice) नहीं है। अपनी विशेष कानूनी समस्या के लिए हमेशा किसी योग्य वकील की सलाह लें।" },
    ],
  },
  en: {
    home: "Home",
    ebooks: "E-books",
    combos: "Combo packs",
    readersTrust: "readers trust us",
    instantDelivery: "✓ Instant digital delivery",
    only: "only",
    taxes: "Inclusive of all taxes",
    off: "OFF",
    digitalOnly: "📄 This is a digital PDF e-book only — no physical / printed copy is shipped.",
    noRefund: "⚠️ Refunds are not possible once the PDF has been downloaded.",
    buyNote: "Secure payment | UPI, Card, Netbanking · No login / account needed",
    pages: "pages",
    instantDownload: "Instant download",
    howToBuy: "How to Buy",
    steps: [
      { label: "Tap Buy", en: "" },
      { label: "Pay", en: "" },
      { label: "Get the PDF", en: "" },
      { label: "My Books", en: "" },
    ],
    comboIncludes: "Books in this combo",
    description: "Description",
    securePayment: "Safe & Secure Payment",
    share: "Share with friends",
    copied: "Link copied",
    faqTitle: "Frequently asked questions",
    relatedTitle: "You may also like",
    relatedBody: "See some of our other important books",
    viewAll: "View all",
    faq: [
      { q: "How will I get this book?", a: "As soon as the payment succeeds you see a Download button and the PDF downloads. The PDF is also sent on WhatsApp to the mobile number you used while paying. The link is saved under ‘My Books’ on this phone, so you can download it again later." },
      { q: "Is the payment safe?", a: "Yes, Razorpay is 100% secure. Pay with Google Pay, PhonePe, Paytm or a card." },
      { q: "Can I read it on my phone?", a: "Yes! The PDF opens on any phone, laptop or tablet." },
      { q: "Is this a physical book?", a: "No. It is a fully digital PDF e-book. No printed / hard copy is shipped." },
      { q: "On how many devices can I read it?", a: "There is no device limit — read it on your mobile, tablet, laptop or desktop." },
      { q: "Will I get updates in future?", a: "When the law changes in an important way we publish an updated edition. The current version is mentioned on the product page." },
      { q: "Does this book give legal advice?", a: "No. This book is for reference and education only. It is not legal advice of any kind. Always consult a qualified advocate for your specific legal problem." },
    ],
  },
} satisfies Record<Locale, unknown>;

/** Preview viewer labels — same language rule as PRODUCT_COPY. */
export const GALLERY_COPY = {
  mr: { page: "पान", prev: "मागील", next: "पुढील", prevPage: "मागील पान", nextPage: "पुढील पान", swipe: "स्वाईप करा ›", cover: "कव्हर", freePreview: (n: number) => `पहिली ${n} पाने मोफत वाचा (Preview)`, readLarge: "मोठ्या आकारात वाचा", close: "बंद करा", reader: "नमुना प्रत वाचक", buy: "खरेदी करा", buyFull: "संपूर्ण पुस्तक खरेदी करा", loading: "पाने उघडत आहेत…", failed: "नमुना पाने उघडता आली नाहीत. कृपया पुन्हा प्रयत्न करा.", zoomIn: "मोठे करा", zoomOut: "लहान करा", rotate: "फिरवा" },
  hi: { page: "पृष्ठ", prev: "पिछला", next: "अगला", prevPage: "पिछला पृष्ठ", nextPage: "अगला पृष्ठ", swipe: "स्वाइप करें ›", cover: "कवर", freePreview: (n: number) => `पहले ${n} पृष्ठ मुफ्त पढ़ें (Preview)`, readLarge: "बड़े आकार में पढ़ें", close: "बंद करें", reader: "नमूना प्रति रीडर", buy: "खरीदें", buyFull: "पूरी किताब खरीदें", loading: "पृष्ठ खुल रहे हैं…", failed: "नमूना पृष्ठ नहीं खुल सके। कृपया फिर से कोशिश करें।", zoomIn: "बड़ा करें", zoomOut: "छोटा करें", rotate: "घुमाएँ" },
  en: { page: "Page", prev: "Previous", next: "Next", prevPage: "Previous page", nextPage: "Next page", swipe: "Swipe ›", cover: "Cover", freePreview: (n: number) => `Read the first ${n} pages free`, readLarge: "Read full screen", close: "Close", reader: "Sample reader", buy: "Buy", buyFull: "Buy the full book", loading: "Opening pages…", failed: "Could not open the sample pages. Please try again.", zoomIn: "Zoom in", zoomOut: "Zoom out", rotate: "Rotate" },
} satisfies Record<Locale, unknown>;

export type GalleryCopy = (typeof GALLERY_COPY)[Locale];
