"use client";
import { useMemo, useState } from "react";
import { saveStoreSettings } from "@/app/dashboard/actions";
import { Field, fieldClass, MissingItems, ProgressBar, SaveButton, SectionCard } from "@/components/admin/OnboardingUI";

const required: Array<[string, string]> = [["hero_title", "homepage headline"], ["hero_text", "homepage supporting text"], ["about_text", "company story and mission"], ["director_profile", "director or proprietor profile"]];

export default function ContentForm({ initial, baseCompleted, totalRequirements }: { initial: Record<string, string | boolean>; baseCompleted: number; totalRequirements: number }) {
  const [values, setValues] = useState(initial); const [photoNames, setPhotoNames] = useState<Record<number, string>>({});
  const set = (key: string, value: string | boolean) => setValues((current) => ({ ...current, [key]: value })); const text = (key: string) => String(values[key] ?? "");
  const missing = useMemo(() => required.filter(([key]) => !String(values[key] ?? "").trim()).map(([, label]) => label), [values]);
  const percent = Math.round(((baseCompleted + required.length - missing.length) / totalRequirements) * 100);
  return <><div className="mb-5 grid gap-3 lg:grid-cols-2"><ProgressBar percent={percent} /><MissingItems items={missing} /></div><form action={saveStoreSettings} className="space-y-5" encType="multipart/form-data"><input type="hidden" name="scope" value="content" /><input type="hidden" name="return_to" value="/dashboard/integrations" />{[1,2,3].map((n) => <input key={n} type="hidden" name={`testimonial_${n}_photo_url`} value={text(`testimonial_${n}_photo_url`)} />)}
    <SectionCard title="Homepage"><div className="space-y-4"><TextInput label="Main headline" name="hero_title" value={text("hero_title")} set={set} /><TextArea label="Supporting text" name="hero_text" value={text("hero_text")} set={set} rows={3} /></div></SectionCard>
    <SectionCard title="About the business"><div className="space-y-4"><TextArea label="Company story and mission" name="about_text" value={text("about_text")} set={set} rows={6} /><TextArea label="Director or proprietor profile" name="director_profile" value={text("director_profile")} set={set} rows={4} /></div></SectionCard>
    <SectionCard title="Customer testimonials (optional)" description="Add only testimonials approved for public display."><div className="grid gap-4">{[1,2,3].map((n) => <details key={n} className="rounded-xl border border-brand-100 p-4"><summary className="cursor-pointer text-sm font-bold text-brand-800">Testimonial {n}</summary><div className="mt-4 grid gap-3 sm:grid-cols-2"><TextInput label="Customer name" name={`testimonial_${n}_name`} value={text(`testimonial_${n}_name`)} set={set} /><TextInput label="City" name={`testimonial_${n}_city`} value={text(`testimonial_${n}_city`)} set={set} /><div className="sm:col-span-2"><TextArea label="Testimonial" name={`testimonial_${n}_text`} value={text(`testimonial_${n}_text`)} set={set} rows={3} /></div><Field label="Customer photo"><input type="file" name={`testimonial_${n}_photo_file`} accept="image/*" className={fieldClass} onChange={(e) => { const f=e.target.files?.[0]; if(f) setPhotoNames((c)=>({...c,[n]:f.name})); }} />{photoNames[n] && <span className="mt-1 block text-[11px] font-semibold text-green-600">Selected: {photoNames[n]}</span>}</Field><label className="flex items-center gap-2 text-xs font-semibold text-brand-700"><input type="checkbox" name={`testimonial_${n}_consent`} checked={values[`testimonial_${n}_consent`] === true} onChange={(e)=>set(`testimonial_${n}_consent`,e.target.checked)} className="h-4 w-4 accent-brand-teal" /> Written publication consent received</label></div></details>)}</div></SectionCard>
    <SectionCard title="Social links (optional)"><div className="grid gap-4 sm:grid-cols-3">{["instagram_url","facebook_url","youtube_url"].map((name)=><TextInput key={name} type="url" label={name.split("_")[0].replace(/^./,l=>l.toUpperCase())} name={name} value={text(name)} set={set} />)}</div></SectionCard><div className="flex justify-end"><SaveButton>Save and continue</SaveButton></div>
  </form></>;
}
function TextInput({label,name,value,set,type="text"}:{label:string;name:string;value:string;set:(k:string,v:string)=>void;type?:string}){return <Field label={label}><input type={type} name={name} value={value} onChange={(e)=>set(name,e.target.value)} className={fieldClass}/></Field>}
function TextArea({label,name,value,set,rows}:{label:string;name:string;value:string;set:(k:string,v:string)=>void;rows:number}){return <Field label={label}><textarea name={name} value={value} rows={rows} onChange={(e)=>set(name,e.target.value)} className={fieldClass}/></Field>}
