"use client";
import { useState } from "react";
import { saveStoreSettings } from "@/app/dashboard/actions";
import { Field, fieldClass, ProgressBar, SaveButton, SectionCard } from "@/components/admin/OnboardingUI";

const checks = ["legal_approved","staging_approved","payment_tested"] as const;
export default function LaunchApprovalForm({ initial, baseCompleted, totalRequirements }: { initial:Record<string,string|boolean>;baseCompleted:number;totalRequirements:number }){
 const [values,setValues]=useState(initial); const done=checks.filter((key)=>values[key]===true).length; const percent=Math.round(((baseCompleted+done)/totalRequirements)*100); const text=(key:string)=>String(values[key]??"");
 return <><div className="mb-5"><ProgressBar percent={percent} label={`${done} of 3 final approvals complete`}/></div><form action={saveStoreSettings}><input type="hidden" name="scope" value="launch"/><input type="hidden" name="return_to" value="/dashboard/launch"/><SectionCard title="Formal approval record" description="Progress updates when each approval is checked."><div className="space-y-3"><Approval name="legal_approved" checked={values.legal_approved===true} set={(v)=>setValues((x)=>({...x,legal_approved:v}))}>The client approved all legal policies.</Approval><Approval name="staging_approved" checked={values.staging_approved===true} set={(v)=>setValues((x)=>({...x,staging_approved:v}))}>The client approved staging, branding, content and prices.</Approval><Approval name="payment_tested" checked={values.payment_tested===true} set={(v)=>setValues((x)=>({...x,payment_tested:v}))}>A real payment, PDF download and optional WhatsApp delivery were tested.</Approval><div className="grid gap-4 pt-3 sm:grid-cols-2"><Field label="Approved by"><input name="approved_by" value={text("approved_by")} onChange={(e)=>setValues((v)=>({...v,approved_by:e.target.value}))} className={fieldClass}/></Field><Field label="Approval reference"><input name="approval_reference" value={text("approval_reference")} onChange={(e)=>setValues((v)=>({...v,approval_reference:e.target.value}))} className={fieldClass}/></Field></div><div className="pt-2"><SaveButton>Save approval status</SaveButton></div></div></SectionCard></form></>;
}
function Approval({name,checked,set,children}:{name:string;checked:boolean;set:(v:boolean)=>void;children:React.ReactNode}){return <label className="flex gap-3 rounded-xl border border-brand-100 p-4"><input type="checkbox" name={name} checked={checked} onChange={(e)=>set(e.target.checked)} className="mt-0.5 h-5 w-5 shrink-0 accent-brand-teal"/><span className="text-sm text-brand-700">{children}</span></label>}
